### ISSUE TITLE
The character '0' (zero) is appended to words that lack punctuation 

### ISSUE THREAD

**Issue by nilsdacke** [alvenirai/punctfix#10]
The following lines (line 196, inference.py)

        if label[0] != "O":
            word += label[0]

have the effect of appending a '0' (zero) character to output words that have no punctuation. Should be 

        if label[0] != "0":  # <-- zero, not oh
            word += label[0]

**Comment by zer0x42** [comment]
Hi @nilsdacke, thanks for posting the issue and addressing it with a PR :-)

Could you provide more context and an example of where the issue occurred in your use-case?

Our label map is:
        "0": "OU",
        "1": "OO",
        "2": ".O",
        "3": "!O",
        "4": ",O",
        "5": ".U",
        "6": "!U",
        "7": ",U",
        "8": ":O",
        "9": ";O",
        "10": ":U",
        "11": "'O",
        "12": "-O",
        "13": "?O",
        "14": "?U"
        
The idea is that if the first character of a label is "O" then we add no punctuation, and if it is not "O" we add the first character as the punctuation - so using "O" as an identifier is intentional on our part.

Essentially your commit introduces the exact issue you are trying to fix (c.f. unit tests in the PR) so we need a bit more information on the issue to address it.

**Comment by nilsdacke** [comment]
Hi,

Thanks for the reply and for the nice tool :-)

I see, if you use 'O' to represent no punctuation, then it works. I thought
it was '0' (zero).

However, line 202 of inference.py has:

        if label[0] != "0" and label[0] in [".", "!", "?"]:
            next_auto_uppercase = True

which seems to suggest that '0' (zero) is used. (In the line above it makes
no functional difference as the comparison to '0' is redundant.)

Which is the more conventional choice, '0' (zero) or 'O' (oh)?

Thanks,

- Simon

**Comment by zer0x42** [comment]
Good catch! That's a mistake on our end - the comparison to "0" can and should be removed. 

If you feel like updating your PR with the removal we'd be happy to merge it :-)

As for conventions we have gone for 'O' (oh) over 0 (zero) due to it's use as a blank in NER tagging tasks, whether or not that makes it a conventional choice I'll leave for you to decide.

- Martin

**Comment by sorenmulli** [comment]
Hi @nilsdacke , we will remove this superfluous check, thank you for making us aware of it.
If you have an example where "0" (zero) is appended to a word, we would be very happy to see it.

-- Søren
